### ISSUE TITLE
Set MongoDB version across different plugin executions

### ISSUE THREAD

**Issue by yacota** [joelittlejohn/embedmongo-maven-plugin#51]
If maven property "embedmongo.version" is no set one have to set it as follows

    <plugin>
                <groupId>com.github.joelittlejohn.embedmongo</groupId>
                <artifactId>embedmongo-maven-plugin</artifactId>
                <version>0.3.0</version>
                <configuration>
                    <version>2.7.5</version> 
                </configuration>
                <executions>
                     ...

Otherwise If you use the goals start and mongo-import they will have different MongoDb versions.
See the following output

    [INFO] --- embedmongo-maven-plugin:0.3.0:start (start) @ ctv-pubfrontal-core ---
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip START
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip DONE
    ...
    [INFO] --- embedmongo-maven-plugin:0.3.0:mongo-import (mongo-import) @ ctv-pubfrontal-core ---
    ...
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.2.1.zip START 
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.2.1.zip DONE

So the behaviour of this "version" property is not the same as "port", which is stored in order be accessible from all the executions. This is absolutely fine but must be well documented IMHO

But note than when setting embedmongo.version as a property in my pom.xml MongoDb is extracted twice although using the same version, which I think is not the desired behaviour

    [INFO] --- embedmongo-maven-plugin:0.3.0:start (start) @ ctv-pubfrontal-core ---
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip START
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip DONE
    [INFO] --- embedmongo-maven-plugin:0.3.0:mongo-import (mongo-import) @ ctv-pubfrontal-core ---
    [WARNING] Unrecognised MongoDB version '2.7.5', this might be a new version that we don't yet know about. Attemping download anyway...
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip START
    Extract C:\Users\jllach\.embedmongo\win32\mongodb-win32-x86_64-2.7.5.zip DONE

Maybe this happens because is an unrecognised version ?

**Comment by joelittlejohn** [comment]
These goals have been deliberately kept separate to try and maximise their usefulness, so you can use `mongo-import` without using `start` if you wish. This is what's causing the double extraction, these are completely isolated invocations. I don't think it's possible to reuse an existing extraction because of the way the flapdoodle API works - each process has its own Starter class and when this class is 'prepared' it extracts.

Port is something that can be randomly generated by `start`, so for that property it's important that we publish the value in a way that other plugins can use. This isn't quite the same with version, and I think if you want to set a single version across all plugins then you should set this globally in the pom as you describe.

**Comment by yacota** [comment]
Thanks for the explanation, but I was not expecting this behaviour once read the available documentation
Maybe I have missed something. Thanks again

**Comment by joelittlejohn** [comment]
Ah, I see that `version` was missing from the docs for the other goals. I've fixed this now.
